CMSIS-compatible ARM Cortex-M ports
weston-embedded/uC-OS2 pull request #1
Opened 2020-06-07 17:08 UTC by quantum-leaps

The ARM Cortex-M ports (Ports/ARM-Cortex-M directory) have been modified to comply with CMSIS. Specifically, the PendSV and SysTick exception handlers have been renamed to the CMSIS-compliant names PendSV_Handler (originally was OS_CPU_PendSVHandler) and SysTick_Handler (originally was OS_CPU_SysTickHandler). This change is necessary for the uC/OS-II applications to be able to use the CMSIS-compliant startup code.

2020-06-08 14:59 UTC, quantum-leaps commented
Updated some assembly files in the ARMv6-M directory.

2021-03-17 01:50 UTC, cwoodall commented
@quantum-leaps under what conditions i this necessary? I just installed these handlers manually (by creating them locally and then calling these C functions). that is obviously not very efficient.

2021-03-17 02:14 UTC, quantum-leaps commented
Hi Christopher,
I'm not sure your question as to "under what conditions i this necessary?".

The unmodified uC/OS-II ports to ARM Cortex-M use names for exceptions and IRQs that are **NOT conformant** with CMSIS. Specifically, CMSIS requires that the handler for the PendSV exception be named PendSV_Handler.

So, my change is all about compliance with the CMSIS standard. This, in turn, allows the uC/OS-II ports to ARM Cortex-M be usable with the CMSIS-compliant startup code, which provides CMSIS-compliant interrupt vector table.

I hope that my comments make sense to you.

--Miro

2021-03-17 18:09 UTC, forg0ne commented
This approach can break backwards compatibility with existing projects.
I'd recommend adding a new label to the asm files, and a wrapper for the C functions.
This will give you CMSIS compatibility without breaking projects that use the existing names.

2021-03-17 18:10 UTC, forg0ne commented
Additionally, the merge target should be develop, not master.

2021-05-03 22:02 UTC, forg0ne requested changes
This approach can break backwards compatibility with existing projects that use the old handlers.
We cannot merge these changes while this is a concern.
Please review my comment about how to add CMSIS compatibility while maintaining backwards compatibility.

2021-06-16 15:52 UTC, closed without merging